reactioncommerce/example-storefront

src/components/Layout/Layout.js, src/pages/_document.js
Use react helmet in place of `next/head`
1. Run the app and ensure title/meta and other header attributes appear in the head
=> feat: Add react helmet support

package-lock.json, package.json, src/components/Header/Header.js, src/lib/stores/UIStore.js, src/lib/stores/index.js, src/lib/theme/withRoot.js, src/pages/_document.js, src/pages/index.js, src/server.js
Add a UIStore and cart open/close example
1. Click the cart button
2. see cart open
3. click on the cart overlay
4. see cart close
=> feat: Add mobx UIStore and example

src/pages/_document.js
Updated the google fonts link to be Source Sans Pro 200, 400 & 700
[Typography Guidelines](https://zpl.io/agGQ9o9)
=> feat: updated google fonts href to be source sans pro

package.json, src/components/Navigation/DesktopNavigationItem.js, src/components/Navigation/MobileNavigationItem.js, src/pages/_document.js, src/routes.js, src/server.js
This PR adds next-routes integration to provide a better dynamic routing solution.
=> feat: integrate next-routes package to provide dynamic routing.

docker-compose.yml, yarn.lock
Not really a fix but it avoids errors if you accidentally do `yarn add` outside of docker
=> chore: `yarn install` on every `docker-compose up`

src/routes.js
Issue #19 
Impact: minor
Type: feat/refactor
Add routes for `/product` and `/shop/product`
- Add a route for `/shop/product`
- Update route for `/product` to match same param names as `/shop/product`
none
1. With the app running and preconfigured using steps in the readme...
1. Navigate to `http://localhost:4000/product/1234` and see PDP page
1. Navigate to `http://localhost:4000/shop/my-shop/product/1234` and see PDP page
=> feat: add and update PDP routes

.gitignore
Impact: minor
Type: chore
Ignore reports directory from junit
=> chore: ignore reports directory

.eslintignore, src/components/Footer/Footer.js, src/components/Header/Header.js, src/components/Link/Link.js, src/components/MediaGalleryItem/MediaGalleryItem.js, src/components/ProductDetail/__mocks__/productData.mock.js, src/components/TagGrid/TagGrid.js, src/lib/theme/getPageContext.js
The shop name in the header now links back to home page.
=> fix: make shop name in header link to home

README.md, docs/MOBX.md, src/lib/stores/AuthStore.js, src/lib/stores/RoutingStore.js, src/lib/stores/UIStore.js
Start adding documentation for our MOBX stores.
=> add mobx documentation

.circleci/config.yml, .snyk
Updated `.snyk` to ignore vulnerable deps that can't be updated.
=> chore: fix snyk issues

README.md
Update the README docs to be more clear in regards to setup, developing, running commands including tests within the container and more.
=> chore: update docs in readme

src/components/ProductGrid/ProductGrid.js, src/components/ProductGrid/ProductGrid.test.js, src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap, src/components/ProductGridHero/ProductGridHero.js, src/components/ProductGridHero/ProductGridHero.test.js, src/components/ProductGridHero/__snapshots__/ProductGridHero.test.js.snap, src/components/Select/Select.js, src/components/Select/__snapshots__/Select.test.js.snap, src/components/SortBySelector/README.md, src/components/SortBySelector/SortBySelector.js, src/components/SortBySelector/SortBySelector.test.js, src/components/SortBySelector/__snapshots__/SortBySelector.test.js.snap, src/components/SortBySelector/index.js, src/pages/index.js
This PR add a sort by selector to the the product grid, it does not include wiring to a GraphQL endpoint.
**Testing** 
1. Run app
2. Verify component renders correctly.
=> Feature: add sort by selector

docs/page-architecture.md
This PR provides documentation on page architecture.
=> Add page architecture documentation

package.json, src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap, src/components/ProductItem/ProductItem.js, src/components/ProductItem/__snapshots__/ProductItem.test.js.snap, yarn.lock
This PR adds the [Reaction Component Library](https://github.com/reactioncommerce/reaction-component-library) to the starterkit, and uses it's `Price` component to display the product price on the Product Grid.
- Basically, nothing should seem different
- Change pricing data on the core reaction app
- See pricing data update on the starterkit
=> feat: use component library Price component for pricing on Grid

src/components/Header/Header.js, src/components/Header/Header.test.js, src/components/NavigationDesktop/NavigationItemDesktop.js, src/components/NavigationDesktop/__snapshots__/NavigationItemDesktop.test.js.snap, src/components/ProductGridHero/ProductGridHero.js, src/components/ProductGridHero/__snapshots__/ProductGridHero.test.js.snap
Small updates to bring the starterkit closer to matching our designs.
- Nav bar background coloring & border
- Nav bar "logo"
- Nav bar item capitalization
- Margins around hero image
=> UI updates to better match designs

package.json, src/components/Header/Header.js, src/components/Layout/Layout.js, src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap, src/pages/_app.js, src/pages/cart.js, src/pages/checkout.js, src/routes.js, yarn.lock
Resolves #167
Impact: Minor
Type: Feature
Add checkout page component and corresponding route, placeholders are used for component not yet built.
=> Feat add checkout page and component placeholders

.env.example, next.config.js, src/lib/utils/favicons.js, src/pages/_document.js
Resolves #99 
Impact: minor
Type: feature
Adds favorites icons 
1. Verify favorite icon links are rendered in the HTML markup
=> feat: add favicons

package.json, src/components/AccountDropdown/AccountDropdown.js, src/components/AccountDropdown/__snapshots__/AccountDropdown.test.js.snap, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap, src/components/CartItems/CartItems.js, src/components/CartPopover/__snapshots__/CartPopover.test.js.snap, src/components/Header/Header.js, src/components/MediaGallery/__snapshots__/MediaGallery.test.js.snap, src/components/MiniCart/MiniCart.js, src/components/MiniCart/MiniCart.test.js, src/components/MiniCart/__snapshots__/MiniCart.test.js.snap, src/components/MiniCart/index.js, src/components/NavigationDesktop/__snapshots__/NavigationItemDesktop.test.js.snap, src/components/NavigationMobile/__snapshots__/NavigationItemMobile.test.js.snap, src/components/PageSizeSelector/__snapshots__/PageSizeSelector.test.js.snap, src/components/PageStepper/__snapshots__/PageStepper.test.js.snap, src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap, src/components/ProductDetailAddToCart/__snapshots__/ProductDetailAddToCart.test.js.snap, src/components/ProductDetailInfo/__snapshots__/ProductDetailInfo.test.js.snap, src/components/ProductDetailOptionsList/__snapshots__/ProductDetailOptionsList.test.js.snap, src/components/ProductDetailTitle/__snapshots__/ProductDetailTitle.test.js.snap, src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap, src/components/ProductGridHero/__snapshots__/ProductGridHero.test.js.snap, src/components/Select/__snapshots__/Select.test.js.snap, src/components/SortBySelector/__snapshots__/SortBySelector.test.js.snap, src/components/TagGrid/__snapshots__/TagGrid.test.js.snap, src/components/VariantList/__snapshots__/VariantList.test.js.snap, src/pages/cart.js, yarn.lock
Impact: minor
Type: feature
Integrates `MiniCart` component that will be rendered on hover over the cart icon. Further, clicking on the cart icon will result in the user being taken to the cart page.
1. Hover over cart icon and verify mini cart is rendered
2. Click on cart icon and verify user is taken to the cart page.
=> Feature: integrate mini cart

package.json, src/components/CartPopover/__snapshots__/CartPopover.test.js.snap, src/components/CheckoutButtons/CheckoutButtons.js, src/components/CheckoutButtons/__snapshots__/CheckoutButtons.test.js.snap, src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap, src/components/ProductDetailAddToCart/__snapshots__/ProductDetailAddToCart.test.js.snap, src/pages/checkout.js, src/routes.js, yarn.lock
Resolves #180 
Impact: minor
Type: style 
Update checkout page to match designs
1. Verify checkout page matches designs
=> Update checkout page styles

package.json, src/components/NavigationDesktop/__snapshots__/NavigationItemDesktop.test.js.snap, src/components/PageStepper/__snapshots__/PageStepper.test.js.snap, src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap, src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap, src/components/TagGrid/__snapshots__/TagGrid.test.js.snap, src/componentsContext.js, src/pages/_document.js, src/pages/checkout.js, yarn.lock
Impact: minor
Type: feature
This PR adds the groundwork to start integration `CheckoutActions` components and its underlying components.
1. Start app 
2. Navigate to /checkout
3. verify page renders mocked shipping checkout action.
=> Groundwork for  CheckoutActions component integration

package.json, src/pages/_app.js, src/pages/checkout.js, src/pages/login.js, yarn.lock
Resolves #247 
Impact: major
Type: feature
Integrates the `CheckoutActions` component and underlying components. Configures stripe elements and wires up checkout actions to collect user data in checkout page.
1. Clear localStorage
2.  Add item to cart
3. Click on "Checkout" either on cart page or mini cart popper
4. Enter email to checkout as guest
5. Verify guest's email is rendered on checkout page
1. Enter shipping information
2. Click "Save and Continue" 
3. Click on change next to saved shipping info
4. Verify shipping info was updated
1. Enter payment info: use Credit card number: 41111111111111111 and any valid expiry date and CVC
2. Click on "Save and Continuer"
3. Verify payment info was saved
=> Integrate checkout actions Part 1

.env.example, docs/page-architecture.md, src/components/Layout/Layout.js, src/components/MiniCart/MiniCart.test.js, src/components/ProductDetail/ProductDetail.js, src/pages/_document.js, src/pages/_error.js, src/pages/cart.js, src/pages/checkout.js, src/pages/index.js, src/pages/login.js, src/pages/product.js, src/pages/tag.js
Resolves #215 
Type: **bugfix | refactor**
`<head>` tags created on the server by React-Helmet would be replaced after storefront loaded causing general `meta`, `script` and `link` tags to be removed losing the favicon and font resources.
* Refactor of the `_document.js` page component to make static `head` tags a responsibility of `next/Head`. This leaves any dynamic `head` tags (title, meta:og, meta:description, JSON-LD) the responsibility of `Helmet` within each page component.
* Removed `<Helmet />` and `title` prop from `Layout` component since it's being overwritten.
* Updated/normalized the usage of `<Helmet />` in all page components.
* Moved `<Helmet />` and the JSON-LD creation out of the `ProductDetail` component and up to the `Product` page component.
* Added …
=> (refactor): moving static head tags out of react-helmet

src/components/MiniCart/MiniCart.js, src/components/MiniCart/__snapshots__/MiniCart.test.js.snap
Resolves #301 
Cart icon has no quantity badge.
Added a quantity badge.
None.
=> feat: Add cart badge

Dockerfile
Resolves #345 
Impact: Major
Type: feature
This PR updates our docker image to use Node 10. I have tested the storefront for a couple of days and have found any problems.
1. Start storefront with: `docker-compose up --build`
2. Complete the checkout process as a logged in user + anonymous
3. Verify no errors occur.
More detail for what each of these sections should include are available in our [Contributing Docs](https://docs.reactioncommerce.com/reaction-docs/master/contributing-to-reaction)
=> feature: update node to version 10

package.json, src/components/CartItems/CartItems.js, src/components/CheckoutActions/CheckoutActions.js, src/components/CheckoutSummary/CheckoutSummary.test.js, src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap, src/components/OrderFulfillmentGroup/OrderFulfillmentGroup.test.js, src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap, src/components/OrderFulfillmentGroups/OrderFulfillmentGroups.test.js, src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap, src/components/OrderSummary/OrderSummary.test.js, yarn.lock
Resolves #385 
The URL for Products created by several components, `Cart`, `MiniCart`, `FinalReviewCheckoutAction`, does not allow for more complex routes beyond simply a `/product-slug`. Currently, neither the product title links, nor the product image links in the Cart, MiniCart, Cart in Checkout, and FinalReviewCheckoutAction do not link properly to the product.
none
1. MiniCart from Grid page, from a tagged product's page
2. Sidebar of Checkout
3. Cart
4. FinalReviewCheckoutAction
1. MiniCart on Grid/PDP pages: http://localhost:4000/
2. Sidebar of Checkout page: http://localhost:4000/cart/checkout
3. Cart: http://localhost:4000/cart/
4. FinalReviewCheckoutAction, after filling in all the steps: http://localhost:4000/cart/checkout
5. Thank You page
=> fix(385): Fix Product title & image URLs in Cart, MiniCart, FinalReviewCheckoutAction

package.json, yarn.lock
- InlineAlert bugfix
- Switching billingAddress fix
- Save `fullName` on address
=> chore: upgrade reactioncommerce/components to latest

src/lib/apollo/withApolloClient.js
=> fix: Add null check

README.md
=> docs: how to debug the server with devtools

docs/tags.md
Type: **docs|chore**
- Update Tag Listing Page docs with info on sitemap, `isVisible`
=> docs(tags): update tag docs to include sitemap, isVisible

README.md
Resolves N/A
Type: **docs**
Typo on README.md.
Fix typo.
=> docs: Fix minor typo on README.md

README.md
removes broken link from readme.md
=> removes fossa status from readme

CHANGELOG.md, README.md, package.json
Updates the CHANGELOG and the README in preparation for the release of 2.0.0
Also bumps the `package.json` to 2.0.0
=> Chore: update the CHANGELOG and README and bump to 2.0.0

CHANGELOG.md, package.json
Example Storefront v2.2.1 is a patch update to keep this project in sync with [Reaction v2.2.1](https://github.com/reactioncommerce/reaction) and [reaction-hydra v2.2.1](https://github.com/reactioncommerce/reaction-hydra)
=> version 2.2.1

CHANGELOG.md, package.json
Pulling changes from `master` back into `develop` after the latest release.
=> Syncing develop with master after release v2.2.1

.circleci/config.yml
Small fixes to the `create-gitops-pull-request` CircleCI job.
=> Automated PR fixes

.circleci/config.yml, CHANGELOG.md, package.json
Pull release 2.7.0 changes back into develop
=> Pull release 2.7.0 changes back into develop

.circleci/config.yml
Updated `create gitops pull request job` to use [ci-scripts](https://github.com/reactioncommerce/ci-scripts)
=> enhanced create gitops pull request job

CHANGELOG.md, package.json
Reverts reactioncommerce/example-storefront#605
=> Revert "release v2.9.0"

src/containers/cart/withCart.js
Signed-off-by: trojanh <rajan.tiwari@kiprosh.com>
Resolves https://github.com/reactioncommerce/reaction/issues/4642
Type: **refactor**
Address https://github.com/reactioncommerce/reaction/issues/4642 in backend along with front-end change
=> refactor: update token name cartToken for APIs

.env.example, CHANGELOG.md, package.json, src/config.js, src/serverAuth.js
Example Storefront v2.9.1 is a patch update to keep this project in sync with [Reaction v2.9.1](https://github.com/reactioncommerce/reaction).
- fix: login from storefront [#633](https://github.com/reactioncommerce/example-storefront/pull/633)
=> chore: release v2.9.1
