- .env.example
- README.md
- next.config.js
- src/browser.config.example.js
- src/containers/tags/withNavigationTags.js
- src/lib/apollo/initApolloBrowser.js
- src/lib/apollo/initApolloServer.js
Consolidate values from `browser.config.js` into `.env` having an internal and external GraphQL API URL, and provide those values to server and client.
`src/config.js` remains as it seems `getConfig()` is undefined if included `server.js`. The values in `config.js` aren't needed by anything else, so it seems fine for now.
**Pre-req**: How your `.env` file should look
```
NODE_ENV=development
INTERNAL_GRAPHQL_URL=http://devserver.reaction-api:3030/graphql-alpha
EXTERNAL_GRAPHQL_URL=http://localhost:3030/graphql-alpha
METEOR_TOKEN=${get the Reaction meteor.loginToken from local-storage}
```
1. In `.env` ensure you have a meteor login token set 
2. Start the app with `docker-compose up`. You may need to do `docker-compose down && docker-compose up`
3. See tags show up, as well as `Hello …
> refactor: use next/config for runtime configuration

- src/components/ProductDetail/ProductDetail.js
- src/components/ProductDetail/ProductDetail.test.js
- src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap
- src/components/ProductDetail/sampleData.js
- src/components/ProductDetailTitle/ProductDetailTitle.js
- src/components/ProductDetailTitle/ProductDetailTitle.test.js
- src/components/ProductDetailTitle/__snapshots__/ProductDetailTitle.test.js.snap
- src/components/ProductDetailTitle/index.js
- src/pages/product.js
Issue: #21
Type: **feat**
Create a title component for the PDP page that includes a title and page title if they are passed in as props.
Create a component that can
- Display title & pageTitle
- Display title alone
- Display pageTitle alone
- Not render if neither title nor pageTitle exists
- Start the app and go to `http://localhost:4000/product/1234`
- See Title and Subtitle
> feat: PDP Header (title & pageTitle)

- src/components/ProductDetail/ProductDetail.js
- src/components/ProductDetail/sampleData.js
Issue: #20 
Type: **feat**
Add title and description meta tags to the Product Detail Pag
-Import `react-helmet` into the PDP page file
- add `title` and `meta description` tags via `react-helmet`
- Start the app, go to `http://localhost:4000`, and click any product
- See that title and description meta tags are updated based on the sample data
Better sample sample data is being added in PR #53. If there are conflicts with the sample data in this PR, use the data in #53 instead.
> feat: Add metatags to Product Detail Page

- .circleci/config.yml
- package-lock.json
- package.json
- yarn.lock
Adds `jest-junit` npm lib for junit compatible xml reporting of jest tests. 
Updates the circle `config.yml` file to save test artifacts to reports directory
> chore: update circle config to save artifacts for coverage and junit

- src/components/ProductDetail/ProductDetail.js
- src/components/ProductDetail/__mocks__/productData.mock.js
- src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap
- src/components/TagGrid/TagGrid.js
- src/components/TagGrid/TagGrid.test.js
- src/components/TagGrid/__snapshots__/TagGrid.test.js.snap
- src/components/TagGrid/index.js
Issue: #27 
Type: **feat**
Create a component that displays product tags
- Create a component that displays product tags using the `Chip` component.
- Start the app and go to `http://localhost:4000/product/example-product`
- See the tag grid to the left with sample tags
- Clicking on a tag should take you to a URL like `/tags/<tag-slug>`
> feat: Create PDP tag component

- src/pages/index.js
App would not load correctly if shop name and description were not saved to DB.
This fix checks to make sure that those fields exist before trying to display.
> fix: helmet name undefined when shop name and description not set

- package.json
- src/components/Badge/Badge.js
- src/components/Badge/Badge.test.js
- src/components/Badge/__mocks__/badge.mock.js
- src/components/Badge/__snapshots__/Badge.test.js.snap
- src/components/Badge/index.js
- src/components/ProductDetail/__mocks__/productData.mock.js
- src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap
- src/components/ProductDetailOptionsList/ProductDetailOptionsList.js
- src/components/ProductDetailOptionsList/__snapshots__/ProductDetailOptionsList.test.js.snap
- src/components/ProductGrid/ProductGrid.test.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/components/ProductItem/ProductItem.js
- src/components/ProductItem/__snapshots__/ProductItem.test.js.snap
- src/components/ProductItem/styles.js
- src/components/VariantList/VariantList.js
- src/components/VariantList/__snapshots__/VariantList.test.js.snap
- src/lib/apollo/initApolloBrowser.js
- src/lib/theme/reactionTheme.js
- src/lib/utils/index.js
- src/pages/_document.js
- yarn.lock
Add inventory status badges to variants/options lists. 
**NOTE**: The badge style will be updated when the designers finish the design of the PDP page.
1. Add a new product with a variant and an option and publish the product.
2. By default the variant will have a backorder badge.
3. Verify a backorder badge is visible on the new product variant in the  grid and PDP.
4. Toggle the backorder switch to turn off backordering
5. Grid and PDP should display a "Sold Out" badge
6. Repeat steps 3-5 for the variant option.
> Add inventory status badges to variants and options

- README.md
- package-lock.json
- src/components/ProductGrid/ProductGrid.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/components/ProductItem/styles.js
- src/pages/tag.js
Fixes Issues #65 & #71 
Product grid items have three different sizes. The heights of medium and large items were affecting the grid heights, as there were not stable. In addition, there was no container, so the grid was always full-width
This PR adds a fixed height to product grid images, to keep the grid... a grid. It also adds a 1440px container, as discussed in ticket #71, to contain the grid.
It uses `material-ui-next`s built in CSS-in-JS `sm`, `md`, and `lg` breakpoints.
The PR also adds some docs (a link to the actual Material UI docs).
This PR also removes leftover test code from #59
> fix: image grid sizing issue

- .graphqlrc
- package-lock.json
- package.json
- src/components/MediaGallery/MediaGallery.js
- src/components/ProductDetail/ProductDetail.js
- src/components/ProductDetail/ProductDetail.test.js
- src/components/ProductDetail/__mocks__/productData.mock.js
- src/components/ProductGrid/ProductGrid.js
- src/components/TagGrid/TagGrid.js
- src/components/TagGrid/TagGrid.test.js
- src/components/VariantList/VariantList.test.js
- src/containers/catalog/catalogItemProduct.gql
- src/containers/catalog/catalogItems.gql
- src/containers/catalog/withCatalogItemProduct.js
- src/containers/catalog/withCatalogItems.js
- src/lib/apollo/initApolloBrowser.js
- src/lib/apollo/initApolloServer.js
- src/pages/product.js
- src/routes.js
- yarn.lock
This PR relies on https://github.com/reactioncommerce/reaction/pull/4218 to work (which should hopefully be merged soon)
Updates:
- fetch product item data using URL slug or ID
- update any PDP components with mapped data
- update mock data to match GraphQL data
> fetch data for PDP

- docs/README.md
- docs/utilities.md
- add a utilities docs with a GraphiQl app setup guide
- add a TOC for the testing doc and utils docs to `docs/readme.md`
- reorganize `docs/readme.md` to move architecture decisions doc to the first position. Seems like it's the most important so it should go first.
> docs: add utilities docs

- .snyk
- package.json
- src/components/NavigationDesktop/NavigationItemDesktop.js
- src/components/ProductGrid/ProductGrid.test.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/components/Select/Select.js
- src/components/SortBySelector/SortBySelector.js
- src/components/SortBySelector/SortBySelector.test.js
- src/components/SortBySelector/__snapshots__/SortBySelector.test.js.snap
- src/containers/catalog/catalogItems.gql
- src/containers/catalog/withCatalogItems.js
- src/lib/helpers/pagination.js
- src/lib/stores/RoutingStore.js
- src/lib/stores/UIStore.js
- src/lib/stores/index.js
- src/pages/index.js
- src/pages/tag.js
- yarn.lock
This PR add functionality to sort by updatedAt, price fields.
**Testing**
1. Set sorting to all three values: newest, price: low to high and price: hight to low
2. After each selection verify products are sorted according to the set sort order
---
1. Set sorting to Price: low to high
2. Refresh page
3. Verify sorting persists
---
1. Set sorting
2. Visit PDP page
3. Navigate back to grid 
4. Verify sorting persists
> Wireup sort by selector

- src/components/NavigationDesktop/NavigationItemDesktop.js
- src/components/NavigationDesktop/NavigationItemDesktop.test.js
- src/components/NavigationMobile/NavigationItemMobile.js
- src/components/NavigationMobile/NavigationItemMobile.test.js
- src/components/ProductItem/ProductItem.js
- src/containers/catalog/catalogItems.gql
- src/containers/catalog/withCatalogItems.js
- src/lib/stores/RoutingStore.js
- src/pages/index.js
- src/pages/tag.js
Storing a `tag` inside the `routingStore` that can be used in the `catalogItems` query. 
When a nav item is clicked the `routingStore.tag` will update. 
When a `tag` page is loaded the `routingStore.tag` will be set on page load.
1. Spin up the storefront with several products and tags loaded in RC.
2. Use the tag nav to see the product grid update based on the current tag page.
3. Hard refresh or go directly to a tag page URL to see the product grid load only the products for the active tag.
4. Update the product grid limit or sortBy, then change pages via the tag nav. The product grid should update the products by tag but retain the limit and sortBy properties.
> (feat): 87 nnnnat product grid by tag

- .reaction/project-hooks/README.md
- .reaction/project-hooks/post-build
- .reaction/project-hooks/post-project-start
- .reaction/project-hooks/post-system-start
- .reaction/project-hooks/pre-build
- bin/setup
Issue: none
Impact: minor
Type: chore
We have two projects, `reaction` and `reaction-next-starterkit` that must be coordinated to run together. Keycloak will add a 3rd project and another Docker network. 
Create tooling that will configure and launch the projects with a single CLI command.
Integrate this project with multi-project orchestration.
This PR adds everything needed to hook the project into the [reaction-next](https://github.com/reactioncommerce/reaction-next) meta project. All the existing backends and frontends can be launched with the `make` command. 
After this merge, `make` command in [reaction-next](https://github.com/reactioncommerce/reaction-next) launches:
* Meteor
* Devserver
* Reaction Next Starter Kit
* Keycloak
All user defined networks are automatically created. …
> Reaction Project Hooks

- package.json
- src/components/MediaGallery/MediaGallery.js
- yarn.lock
Renders placeholder image when a product does not have a featured image set.
**Testing**
1. Add a new product in reaction, **WITH OUT** adding any images
2. Verify placeholder image is used in the PDP of the new storefront.
> Renders placeholder image when a product does not have a featured image set.

- .snyk
- src/components/CheckoutButtons/CheckoutButtons.js
- src/components/CheckoutButtons/CheckoutButtons.test.js
- src/components/CheckoutButtons/__snapshots__/CheckoutButtons.test.js.snap
- src/components/CheckoutButtons/index.js
Impact: minor
Type:  feature
Adds a `CheckoutButtons` component that can be used anywhere checkout buttons need to be rendered. Currently there is only one button, in the future more will be added; when other payment methods are supported. For background details as to why this component was created visit: https://github.com/reactioncommerce/reaction-component-library/pull/110
1.  Import component into desired page
2. Verify that checkout button is rendered and it fill the full width of the containing element.
3. Verify clicking on the button takes the user to the `/checkout` URL.
> Feat add checkout buttons component.

- src/components/PageSizeSelector/PageSizeSelector.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/components/ProductItem/__snapshots__/ProductItem.test.js.snap
- src/lib/stores/RoutingStore.js
- src/lib/stores/UIStore.js
- src/lib/stores/index.js
- src/lib/utils/executionEnv.js
- src/lib/utils/pageSizes.js
- src/pages/index.js
Resolves #157 
Impact: minor
Type: refactor
Changing the `limit` url query param manually to a number that is not one of the default page sizes leads to a broken UI state. I attempted to fix that by changing the URL query `limit` param on startup, however it lead to an infinite loop. After some thought, I believe that the we should not be changing the URL query params entered by the user.
A have added validation so that even if an invalid page size is set the URL, the UI will render to using the default page size of 20. 
1. Set page size to any value using the dropdown.
2. Verify URL updates correctly.
3. Change the URL param `limit` and set it to an invalid page size, i.e. 25
4. Verify UI renders with default page size of 20
> Fix invalid page size set via URL param

- src/containers/catalog/withCatalogItemProduct.js
- src/pages/_error.js
Resolves #161 
Impact: minor
Type: feature
Use custom error page and style it according to designs.
Override nextjs' default error page by implementing `_error.js` in pages directory. 
**Testing**
1. Enter a URL of a non existing product or page, i.e. /product/notfound
2. Verify custom error page is rendered.
3. Enter a invalid URL, i.e. /not-found
4. Verify custom error page is rendered.
> Add custom error page

- src/components/ProductGrid/ProductGrid.js
- src/components/ProductGrid/ProductGrid.test.js
- src/components/ProductGrid/ProductGridEmptyMessage.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/containers/catalog/withCatalogItems.js
Resolves #issueNumber
Add message/link to the grid component, when loading is complete but there are no items.
Created a new component, `ProductGridEmptyMessage`, that will display when no products are available on the grid.
None
1. Start up the app
1. Use the Admin to create a tag that has no products attached to it
1. In the starterkit, Go to the tag page which has no products on it
1. See the empty grid message
1. Click the `Clear filters`
1. See that page is routed to where it should go (clear the `querystring`)
> feat: Empty Product Grid "No products" message

- src/components/ProductDetail/ProductDetail.js
- src/containers/catalog/catalogItemProduct.gql
Resolves #165 
Type: **refactor**
Product images aren't displayed based on which variant / option is selected. All images always show, not matter what.
Use the new data available - `media` and `primaryImage` information specific to each option / variant ([PR #4468 in the core repo](https://github.com/reactioncommerce/reaction/pull/4468)) to show only media directly related to the selected option / variant, if available. If no media is available, show the media for the parent of the current selected option / variant.
None
1. Add multiple variants and options to a product
1. Add images to some of these options and variants, and leave some of the options and variants with no images
1. See that when selecting an option / variant, you only see the media that was uploaded for …
> ref: filter media gallery images by selected option / variant

- src/containers/catalog/withCatalogItems.js
- src/containers/tags/withTag.js
- src/pages/index.js
- src/pages/tag.js
Resolves #179 
Data sent to segment was always one click behind, and sometimes it was being sent multiple times with the same or different data.
This was due to two things:
1. The product grid was being remounted every time the page was changed. This was due to the `withCatalogItems` decorator, which was returning `null` while the decorator was loading. This would unmount the grid, which would then remount when the data was ready, which would call `componentDidMount` again.
1. `trackProductListView` was being called as a decorator of `componentDidUpdate`, so it would be called no matter if the data was different or the same, as long as the component did update.
Two issues were occuring here.
1. Don't have `loading` return `null` when data is being …
> fix: Segment receives incorrect Product List Viewed data

- package.json
- yarn.lock
Impact: **critical**
Update `react` and `react-dom` to 16.4.2 to fix XSS vulnerability.
```
✗ Medium severity vulnerability found on react-dom@16.4.1
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/npm:react-dom:20180802
- from: reaction-next-starterkit@1.0.0 > react-dom@16.4.1
Upgrade direct dependency react-dom@16.4.1 to react-dom@16.4.2
```
1. Make sure the app still works
> chore: update react to fix XSS vulnerability

- README.md
Type: **docs**
Add instructions on how to test [reaction-component-library](https://github.com/reactioncommerce/reaction-component-library) components inside of the starterkit
> Add component library test instructions to docs

- package.json
- src/components/CartItems/CartItems.js
- src/componentsContext.js
- src/containers/cart/updateCartItemsQuantityMutation.gql
- src/containers/cart/withCart.js
- src/pages/cart.js
- yarn.lock
Resolves #186
Connect the QuantityInput to the GraphQL mutation `UpdateCartItemsQuantity`
Add a GQL mutation for updateCartItemsQuantity
1. Add items to cart
2. Go to cart page
3. Increment/decrement quantities of items
4. Navigate to the homepage and back to the cart to ensure values have indeed updated
Cart drawer closes when you click on anything so the remove button callback never gets triggered. See #202
> feat: connect quantity input in cart and mini-cart

- src/components/MiniCart/MiniCart.js
Resolves #202
Mini-cart popover would close when you clicked on anything within the popover view.
Remove the `ClickAwayListener` and adjust the logic responsible for closing the popover on a delay to be solely controlled by a timeout.
**test using reaction 1.15.0**
1. Add items to the cart
2. Hover over the mini-cart
3. Try to remove an item from the cart
- The quantity input in the mini-cart doesn't work. See https://github.com/reactioncommerce/reaction-next-starterkit/issues/211
> fix: issue causing mini-cart drawer to close on click

- src/components/MiniCart/MiniCart.js
Resolves #211
Type: **feature/bugfix**
The quantity input in the cart drawer was not hooked up to the `withCart` decorator. This issue revealed itself when the I fixed the issue where the popover would close on click here: https://github.com/reactioncommerce/reaction-next-starterkit/pull/212
- Add event handlers to adjust cart item quantity
**test using reaction 1.15.0**
1. Add an item to the cart
2. Hover over the cart icon to open the mini-cart drawer
3. Adjust the quantity in of the item
4. Hover off of the cart drawer, and back unto it to ensure the changes to the quantity did indeed happen.
It seems as though the quantity input is not reactive for some reason. If you're on the cart page and open the mini-cart drawer and increment the quantity, then the input doesn't …
> bug: Mini-cart quantity hookup

- src/components/NavigationDesktop/NavigationItemDesktop.js
- src/components/NavigationDesktop/__snapshots__/NavigationItemDesktop.test.js.snap
Resolves #196 
Top level tag navigation items are not clickable when rendering in SSR-only when Javascript is disabled.
Wrap top level tags in a `<Link>` component so an `<a>` tag is rendered for SSR / SEO purposes.
None.
1. In Firefox
1. type `about:config` in the address bar and hit enter
1. Search for `javascript.enabled`
1. Double click to disable
1. Launch the starter kit and navigate to the homepage
1. Inspect a top-level nav element with no children, and see that the nav item is an `<a>` tag
> fix: add <Link> to allow nav links to be read by SSR

- .babelrc
Resolves #153 
The storefront wasn't loading in IE11 even though we have ES6 feature polyfills our babelrc config was only targeting the "laster 2 versions" and not IE11.
Updated the babelrc to also target IE11.
1. Startup RC and the storefront.
2. Using a VM visit the storefront app in IE11. (http://10.0.2.2:4000 for VirtualBox)
3. Storefront should now load and navigable
This PR only fixes the issue of the storefront not loading in IE11, as you test you'll see several layout issues that still need to be captured.
> fix: added ie11 to babelrc browser target

- README.md
Update installation docs to reflect that `reaction` is currently on branch `release-1.15.0`, no longer `release-1.2.0`.
> Update docs to reflect current Reaction development branch

- src/components/MiniCart/MiniCart.js
- src/components/MiniCart/__snapshots__/MiniCart.test.js.snap
- src/lib/theme/reactionTheme.js
Resolves #226
When no cart is available, hovering over the cart icon produces an error in the console.
Guard against an empty cart and display a cart empty message with actions.
none
1. With no carts, open the mini cart to see the cart empty message
1. Add an item to the cart, and you should see items in the mini-cart
1. Remove all items from the cart, and you should see the cart empty message in the mini-cart
1. Clicking on "Continue shopping" should take you to the homepage
> bug: Fix broken mini-cart when no cart is available

- package.json
- src/components/MiniCart/MiniCart.js
- yarn.lock
Resolves #233 
When the checkout button in the mini cart was clicked, no event was fired to take you to the checkout page.
- Made an update in the [reaction component library](https://github.com/reactioncommerce/reaction-component-library) to add `onCheckoutButtonClick` to the mini cart checkout button component.
- Hooked up the event callback to a Router.pushRoute in the starter-kit
**Why didn't I use the Link component**
I didn't use the link component because wrapping an anchor tag around a button caused onClick event bubbling issues. I would have to double click the checkout button in order for it to take me to the checkout page.
1. Add items to the cart
2. Open the mini-cart
3. Click the checkout button
4. Arrive at the checkout page
> bug: minicart checkout button onClick hookup

- package.json
- src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/components/ProductItem/__snapshots__/ProductItem.test.js.snap
- src/componentsContext.js
- src/containers/cart/fragments.gql
- src/containers/cart/mutations.gql
- src/containers/cart/withCart.js
- src/lib/theme/reactionTheme.js
- src/pages/_app.js
- src/pages/checkout.js
- src/pages/login.js
- src/routes.js
- yarn.lock
Resolves #225 
*  Updated the `checkout` page to now show a "login/register/checkout as a guest" view if `cart.account === null || !cart.email`.
*  Added the `setEmailOnAnonymousCart` mutation and created a handler for the `withCart` HOC.
*  Added the `GuestForm` component to the login view of the `checkout` page that captures an users email address and sends it to the `setEmailOnAnonymousCart` mutation.
* Added the `CheckoutEmailAddress` component to the `checkout` page  to display the guest/account email once it's avalible.
* Updated cart `fragment` GQL query to include `fulfillmentGroups` and `payments` data.
* Started adding new checkout actions to checkout page.
N/A
1. In the storefront, as an anonymous user add a few items to your cart and click …
> (feat): 225 nnnnat as guest / login checkout

- .snyk
Resolves N/A
Getting snyk warnings for out of date dep in CI.
Update the .snyk ignore file since [next-routes](https://github.com/fridays/next-routes) & [nextjs](https://github.com/zeit/next.js) haven't updated.
1. run `yarn install` followed by `synk test` to verify no security warnings.
> chore: updated snyk ignore file

- package.json
- src/components/CheckoutActions/CheckoutActions.js
- src/components/CheckoutActions/index.js
- src/containers/cart/fragments.gql
- src/containers/cart/mutations.gql
- src/containers/cart/withCart.js
- src/lib/utils/cartUtils.js
- src/pages/checkout.js
- yarn.lock
Resolves #250 
Impact: major
Type: feature
Integrates the `ShippingInformationCheckoutAction` with it's corresponding GraphQL endpoint.
1. Add an item to the shopping cart
2. Click on "Checkout" in the MiniCart 
3. Enter a shipping address
4. Click Save and Continue
5. Verify address was saved correctly
6. Click on "change" next to the shipping address
7. Make a change and click on "Save and Continue"
8. Verify address was updated.
> Integrate shipping address action with GQL endpoint

- src/components/CheckoutSummary/CheckoutSummary.js
- src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap
- src/containers/cart/withCart.js
- src/pages/checkout.js
Resolves #238
Removing the last cart item on the checkout page leaves you with a visually broken and in an in a state where you have no option but to go back
1. Add a cart empty message when there aren't any items in the cart to checkout with.
2. Make cart items read only in checkout so the quantity can no longer be modified at the time of checkout
none
1. With the starter kit and using reaction `release-1.16.0` running...
1. Ensure you have no cart items
1. Navigate to http://localhost:4000/checkout
1. See the cart empty message
1. Click on the `Continue shopping` button to be redirected to the homepage
> fix: checkout empty state

- src/components/CheckoutActions/CheckoutActions.js
- src/lib/stores/CartStore.js
- src/lib/utils/cartUtils.js
Resolves #266 
Impact: Minor
Type: feature
Integrates the `StripePaymentCheckoutAction` with MobX, the stripe token + billing address is stored in the `CartStore` for use with the review order checkout action.
NOTE: To see the user data, add a console log in the checkout page's render method to output the `paymentData` values.
1. Add item to cart,
2. Fill out steps 1-2 in the checkout page
3. Enter 4111 1111 1111 1111 for the credit card number + any valid data + CVC
4. Enter a billing address
5. click "Save and Continue"
6. Verify payment data was outputted in the browser's console.
> feat: integrate stripe payment checkout action

- .env.example
- src/components/Layout/Layout.js
- src/components/MiniCart/MiniCart.js
- src/components/MiniCart/MiniCart.test.js
- src/components/MiniCart/__snapshots__/MiniCart.test.js.snap
- src/components/ProductDetail/ProductDetail.js
- src/lib/stores/UIStore.js
Resolves #255
Open the mini-cart when the add to cart button is clicked
- Move cart state management to the `uiStore`
- Open the cart using the `uiStore`, close it on a delay
none
1. Hover over the cart icon, it should open
1. Move the mouse away from the cart, it should close in 500ms (quickly)
1. Add an item to the cart, see the mini-cart open
1. Mini-cart should close after 3 seconds (so... not so quickly)
1. Add another item to the cart
1. Mouse over the mini-cart before it closes
1. The mini-cart should **not** close after 3 seconds
1. Mouse off of the mini-cart
1. The mini-cart should close in 500ms
1. Resize the window to a mobile size
1. Add an item to the cart
1. You should still see the mobile add to cart slide-out and no mini-cart
> feat: Open mini-cart on add to cart

- src/containers/cart/fragments.gql
- src/pages/_document.js
- src/pages/index.js
Resolves N/A
1. If a reaction shop didn't have a shop description set the storefront's index page would display a page title of "Reaction | null".
2. Adding scripts with innerHTML was causing an unexpected token error in the browser console.
1. Updated how the index page title is created to only add the ` | <shop.description>` to the end of the description if the property is set.
2. Updated how the innerHTML is set on `<script />` tags to use `dangerouslySetInnerHTML` this prevents the output JS from being formatted incorrectly causing the syntax error.
N/A
1. Load the storefront's index page and verify that either: `<shop.name> | <shop.description>` or `<shop.name>` is the page title pattern.
2. In Reaction as an admin add/remove the shop's description …
> fix: null shop description & unexpected token

- src/components/OrderFulfillmentGroup/OrderFulfillmentGroup.js
- src/components/OrderFulfillmentGroup/OrderFulfillmentGroup.test.js
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroup/index.js
- src/components/OrderFulfillmentGroups/OrderFulfillmentGroups.js
- src/components/OrderFulfillmentGroups/OrderFulfillmentGroups.test.js
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
- src/components/OrderFulfillmentGroups/index.js
- src/components/OrderSummary/OrderSummary.js
- src/components/OrderSummary/OrderSummary.test.js
- src/components/OrderSummary/__snapshots__/OrderSummary.test.js.snap
- src/components/OrderSummary/index.js
- src/containers/order/fragments.gql
- src/containers/order/mutations.gql
- src/containers/order/queries.gql
- src/containers/order/withOrder.js
- src/lib/theme/reactionTheme.js
- src/pages/checkoutComplete.js
- src/routes.js
Resolves #244 
Add a checkout complete page
Added a checkout complete page using many existing components from cart and checkout.
none
1. In Reaction, sign in, add items to cart and checkout
1. Run through the checkout process and create an order
1. After the order is created, open Robo3T and look for the newly created order
1. Copy the order id and base64 encode it as `reaction/order:<order-id>`
1. In the starter kit, ensure you're signed in as the same user as reaction with the `meteor-login-token`
1. Then navigate to `http://localhost:4000/checkout/order/<order-id>`
1. See the checkout completed page with all relevant data
> Checkout complete page

- .env.example
- README.md
- docker-compose.yml
- package.json
Renames the Docker network on which the GraphQL enabled web services are
attached.
Platform networks in the Docker environment should be named as
*.reaction.localhost. The localhost TLD is reserved and guaranteed to
not conflict with a real TLD.
ref: reactioncommerce/reaction#4447
Resolves #issueNumber
Impact: major
Type: chore
**Merge Considerations**
- The network is only updated in newly created projects.
- To enable network communication, other projects must use this new network name.
- PRs related to reactioncommerce/reaction#4447 should be coordinated.
> chore: Rename the reaction-api Docker network

- package.json
- src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
- src/lib/stores/RoutingStore.js
- src/pages/_document.js
- yarn.lock
Resolves #263 
On the catalog grid If a `pageSize` filter had been set and then the `sortBy` filter was changed the `pageSize` filter would be reset back to 20. The issue was being caused by trying to compare the `query.limit` which is a string to an int while validating the limit inside the `routingStore`, this validation check would return false every time the `sortBy` field was changed reseting the `pageSize` to `20`. 
Make sure `_query.limit` is converted to an int before the `inPageSizes` validation function is used.
N/A
1. Visit storefront and change the `pageSize` filter to 60 or 100.
2. Now change the `sortBy` filter to HI2LO or LO2HI, the products should reorg and the `pageSize` filter should persist.
3. Load the page directly with the query …
> fix: sortBy filter doesn't reset pageSize filter

- .babelrc
- package.json
- src/components/Entry/__snapshots__/Entry.test.js.snap
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
- src/components/OrderSummary/__snapshots__/OrderSummary.test.js.snap
- src/components/PageLoading/PageLoading.js
- src/components/PageLoading/index.js
- src/components/PageStepper/PageStepper.js
- src/components/ProductGrid/ProductGrid.js
- src/components/ProductGrid/__snapshots__/ProductGrid.test.js.snap
- src/containers/account/withViewer.js
- src/containers/cart/withCart.js
- src/containers/catalog/withCatalogItemProduct.js
- src/containers/catalog/withCatalogItems.js
- src/containers/order/withOrder.js
- src/containers/shop/withShop.js
- src/containers/tags/withNavigationTags.js
- src/containers/tags/withTag.js
- src/containers/tags/withTags.js
- src/lib/apollo/withApolloClient.js
- src/lib/stores/withMobX.js
- src/lib/theme/reactionTheme.js
- src/pages/_app.js
- src/pages/_document.js
- src/pages/product.js
- src/pages/productGrid.js
- src/pages/tag.js
- src/routes.js
- yarn.lock
Need a loading indicator on the grid pages and PDP page when loading is slow.
- Created a `PageLoading` component
- Pass through Apollo `loading` to the wrapped components
- Update pages to show `PageLoading` while Apollo is loading the data
- Made Previous and Next buttons scroll to the top of the page when clicked
- There is an 800 milliseconds delay before the loading spinner will show, to avoid a quick flash of it on fast connections.
NOTE: Designers are working on final loading design. The animated SVG in there now is CC0-licensed and will work for now.
Resolves #200 
1. Load the home page in Chrome and use the Chrome dev tools network tab to turn on throttling to "Slow 3G" speed. Click "Next" button and see that the page scrolls to the top and then …
> Loading states, styled-components SSR, SSR screen width check, fix getInitialProps

- src/components/CheckoutActions/CheckoutActions.js
- src/containers/cart/withCart.js
- src/containers/order/withPlaceStripeOrder.js
- src/pages/checkoutComplete.js
Resolves #302 
Impact: minor
Type: bugfix 
Clear Apollo Client cache after placing an order as an authenticated user.
1. Login as admin
2. Place an order
3. Verify cart page & mini cart do NOT contain cart items
> fix: clear apollo client cache after placing an order as an authenticated user

- src/components/CheckoutActions/CheckoutActions.js
- src/server.js
Related to #272
After completion of login flow, users are always getting redirected to the home page. We should be returning users to the current page being viewed before the OAuth redirect happened.
- Capture page url in the [current] session object, and redirect there after login / logout completion.
N/a
1. Browse to any page on the storefront while not logged in
2. Attempt a login
3. Confirm you get taken back to the page you were viewing before attempting login
> feat: Redirect user to page opened before auth flow started

- src/lib/stores/RoutingStore.js
Query param changes due to pagination mess with the history stack.
Pushed to the stack instead of replacing the current item.
None
1. Load `/`, or a page with pagination
2. Click `Next`
3. Go back (as in the browser's back button/mapping)
4. Before this fix the page you go back to would be wrong, and inconsistent. After, it is always the page you just came from.
> fix: added to browser history stack instead of replacing it

- package.json
- src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
- src/components/OrderSummary/__snapshots__/OrderSummary.test.js.snap
- yarn.lock
Resolves #324 
In the grid, the image `fit` prop was not recalculating when the `CatalogGridItem` component was updated with a different product
Simply called image fit calculation logic on `componentDidUpdate` fixed the issue.
None
1. Load up the starterkit with the catalog sample data
2. Visit homepage, click next, click previous
3. Confirm images all still perfectly fit the square. Previously after clicking previous, portrait images would have white bars on the left/ & right.
> fix: update reaction components version for grid image size fix

- package.json
- yarn.lock
Resolves 302 from the component library: https://github.com/reactioncommerce/reaction-component-library/issues/302
This PR simply updates the component library version to 0.39.3, resolving an infinite loop discovered in the `CatalogGridItem` component.
1. Load the homepage
2. Confirm no CPU spike while app is just sitting idle.
> chore: update components lib to 0.39.3 for grid loop fix

- src/components/MiniCart/MiniCart.js
Resolves reactioncommerce/reaction-component-library#299
Type: **bugfix|style**
Cart popper occasionally gets aligned too far right. It seems to fix itself after the first open, so seems to be related to on-load style differences like some other recent issues.
The empty cart's width was set to `320px`, but the width of the populated cart is `360px`. Because the cart is initially empty on-load, if you happen to open the MiniCart before it populates it will start at `320px` and then resize to `360px`, but keeping the same `translate3d` x value.
Making the empty cart be the same width as the populated cart fixed the issue.
1. Add some items to your cart
2. Refresh any page
3. Try to open the MiniCart popper before the page finishes loading and before the cart has populated
> Fixed MiniCart popper occasionally being drawn at the wrong position.

- README.md
Type: **docs**
The steps were not numbered correctly in Markdown
Manually incremented steps.
1. Look at this rendered tab --> https://github.com/reactioncommerce/reaction-next-starterkit/blob/3e78790e6120690e9cd87aa96d1d24fbc0500fa9/README.md#getting-started
2. Compare with the current rendered Markdown --> https://github.com/reactioncommerce/reaction-next-starterkit#getting-started
> docs: numbering bug

- src/components/OrderFulfillmentGroup/OrderFulfillmentGroup.js
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
Resolves #334 
Impact: minor
Type: bugfix
Add padding to cart items in order complete page.
1. Verify cart items have padding, compare with designs.
> fix: add padding to cart items in order complete page

- src/components/CheckoutActions/CheckoutActions.js
- src/components/MiniCart/MiniCart.js
- src/components/PageLoading/PageLoading.js
- src/components/ProductDetailAddToCart/ProductDetailAddToCart.js
- src/containers/cart/withCart.js
- src/containers/order/withPlaceStripeOrder.js
- src/lib/stores/CartStore.js
- src/lib/stores/UIStore.js
- src/pages/checkoutComplete.js
Resolves #323 
Impact: minor
Type: bugfix
The `MiniCart` popper would occasionally be rendered on the order completed page. This PR fixes that and clears the cart cache on the client instead of querying the server.
1. Place an order
2. Verify cart popper is not rendered at the bottom of the page, and that the cart has been cleared.
> fix: clear a user's cart after placing an order, and remove MiniCart popper from order completed page.

- src/components/Header/Header.js
Impact: minor
Type: bugfix
if a user only provide a first name, then the logged in indicator would display duplicate initials
1. Log in as admin@localhost, the default credentials
2. Verify the logged in indicator displays only one A, which corresponds to the user name Admin
> fix: Duplicated initials in logged in indicator

- .env.example
- package.json
- src/components/AccountDropdown/AccountDropdown.js
- src/components/Entry/Entry.js
- src/components/Header/Header.js
- src/lib/stores/AuthStore.js
- src/server.js
- yarn.lock
Part of reactioncommerce/reaction/issues/4640
When a Starterkit user clicks "Register", we redirect to the Reaction Hydra login page, but it shows the "Sign In" view rather than "Create Account" view.
Pass extra info to Hydra about the specific auth flow the user is going through: Sign up OR Sign in. 
- Extend Passport configuration to allow passing custom field denoting  "signin" or "signup" flow
- Separate `/auth` route into two distinct `/signin` and `signup` routes to allow requirement above (I couldn't find a way around it with single route)
- Changes needed on the Identity provider to use above update is done in reactioncommerce/reaction/pull/4651.
- Update logout function to delete session in Hydra
- fix: Show logout dropdown onclick Viewer when logged in
- Also …
> feat: Add sign in/up info in auth URL generated by Passport

- LICENSE
- README.md
Resolves #326 
Impact: **critical**
We've needed to choose a license for this project.
@saralouhicks @ticean and I met to discuss this and while we're still working on a decision framework for choosing licenses for new projects, we'll use a permissive license, the Apache 2.0 license for this project.
> chore: Set project license to Apache 2.0

- yarn.lock
Resolves #364
As in #364 
This issue seemed to only affect me, and only when NOT on VPN, but it was consistent within those parameters. This fix is confirmed to avoid the error for me.
Manual search/replace in yarn.lock. Probably could also blow it away and regenerate I guess.
1. Normal CI builds should suffice to test this
> fix: Always use https for npm registry

- docs/tracking-events.md
- package.json
- src/components/ProductDetail/ProductDetail.js
- src/containers/cart/withCart.js
- src/lib/tracking/constants.js
- src/lib/tracking/trackProduct.js
- src/lib/tracking/trackProduct.test.js
- src/lib/tracking/utils/getVariantTrackingData.js
- src/pages/cart.js
- yarn.lock
Resolves #360 
Impact: minor
Type: feature
Add tracking for "Product Added" Segment event.
1. Click on a product to enter the product's details page
2. Verify that a "Product Viewed" event was recorded in the Segment dashboard
4. Increment a product's quantity to an arbitrary number
3. Click the "Add to cart" button
4. Verify a "Product Added" was recorded in the Segment dashboard. The event should include the correct quantity and cartId.
5. Login
6. Repeat steps 1-4,
> Add tracking for "Product Added" Segment event

- src/lib/stores/RoutingStore.js
Resolves #348 
Impact: **critical**
Refreshing on pages that use search queries, like the product grid, causes the app to crash due to trying to access `Router` on the server.
Use the Router on the client (browser) only by placing it within an "is browser" conditional.
none
1. With sample data loaded to be able to test other tag grids
2. Navigate to another grid via the menu
3. Page should load
4. Refresh the page manually
5. The page should load properly
6. Ensure query params are properly applied to the page. (number of items per page, the current page, and other filters)
---
1. Disable javascript
1. Ensure query params are properly applied to the page in SSR mode. (number of items per page, the current page, and other filters)
> fix: issue cause by using Router from `next/routes` on the server

- src/containers/catalog/catalogItemProduct.gql
- src/containers/catalog/catalogItems.gql
Resolves #375 
Type: **feature|bugfix|performance|test|style|refactor|docs|chore**
Metafields are not available on the product.
Add the `metafields` field to the GraphQL queries for the grid and PDP.
none
1. Add metafields to a product in Reaction. This is the `Details` section of the PDP sidebar edit form.
2. Using the Apollo developer tools on the starterkit...
3. Visit the PDP page and verify that the cache for `CatalogProduct:<some-id>` has the metafields you added.
4. Do the same for the grid.
> Fix 375: Add metafields to product query

- src/components/ProductDetail/ProductDetail.js
- src/components/ProductDetail/__snapshots__/ProductDetail.test.js.snap
Resolves #284
The mobile view of the PDP page has the components displayed in a different order.
Add a mobile-only layout to the PDP with the components in the correct order. Keep in mind this PR is just a re-organization of the components, not a restyling of them. Issues have been created to address the [Media Gallery](#377) and [Variant List](#376).
none
1. Open a PDP page
2. Check that the desktop layout remains untouched
3. Resize to the viewport to a Mobile phone size
4. Check that the design is in the correct order
> fix: PDP Mobile re-org

- package.json
- src/components/CheckoutActions/CheckoutActions.js
- yarn.lock
Type: **refactor**
The way we save names is a little funky. We have our forms split into `firstName` and `lastName` fields, but we save names inside the data as `fullName`. We do this by combining the `firstName` and `lastName` fields inside the starterkit.
We need to update the form to accept a single `fullName` field, instead of two fields which are combined into a single field. This update fixes the issue in the starterkits mutation of the data. An update to the component library will also be made to make the fields into a single field.
I don't expect any breaking changes, as the two fields are combined into the single field anyway on the backend.
See that fullName data is saved correctly in `cart.shippings.address.fullName` one the Component library PR is merged.
> refactor: unsplit first and last name fields in Checkout saving

- bin/create-hydra-client.js
- src/server.js
Related to reactioncommerce/reaction#4733
and #350
Our initial Hydra bootstrap settings contains some extra fields that are not in use. These are: (i) the `openid` scope that leads to the issuance of and `id_token` (ii) Extra OAuth 2 Grant Types for the starterkit client.
- Remove the scope for id-token. This can be added back intentionally when we decide how we want to use the id-token across our system. Prevent possible leak of tokens. Prevent confusion around what the scopes are for.
- Remove the unused grant types, and limit to only the ones of use.
N/A - Previous functionality works as before
NB: There is a current bug in Starterkit's Component library version. Set the version to `"@reactioncommerce/components": "0.43.0",` in your package.json.
1. Run this branch …
> fix: Remove unused scopes and grant_type

- tests/integration/ssr.test.js
Type: **bugfix|test**
The SSR integration test wasn't actually testing anything, because of how mocha expects async tests.
Used mocha's `done` callback workflow.
```shell
docker-compose exec web yarn test:integration
```
> fix: integration test finished before resolving

- src/components/ProductDetail/ProductDetail.js
- src/containers/catalog/withCatalogItems.js
Resolves #405
Impact: **critical**
SSR was partially broken on the PDP and grid pages.
- Grid: tag pages displaying incorrect products
- PDP: No product detail, only a navbar
**Product Grids**
Use the `@withTag` decorator to load tag info sooner for use in the query for catalog items
**PDP**
Set an initial width for the `@withWidth()` decorator so it renders on the server
None.
1. Disable javascript
2. Navigate between the homepage and the tag grids
3. Ensure expected content is on each. (shirts under /tag/shirts, accessories under tag/accessories, etc)
4. Click into a PDP page
5. Ensure it renders the desired product
---
1. Enable Javascript
2. Navigate the app as in steps 2-6 above, and ensure the pages render as expected
> fix: SSR issues with product grids and PDP pages

- src/components/CheckoutActions/CheckoutActions.js
- src/lib/theme/components.js
- src/pages/_document.js
Resolves #340 
- Issue: A customer does not know if a payment failed, and is stuck at the page when errors occur. 
- Feature: After a customer saves an invalid credit card and clicks Check Out, the customer should be taken back to the Cart page on Step 3, Payment, and an InlineAlert should appear with the error message.
1. Test these Stripe cards pre-configured with errors: https://stripe.com/docs/testing#cards-responses
> fix(340): catch Stripe Payment error and save error message

- next.config.js
Resolves #416 
`canonicalURL` is accessible from server-side, but not client side.
Add `canonicalURL` to `publicRuntimeConfig`
```diff
publicRuntimeConfig: {
+    canonicalUrl: process.env.CANONICAL_URL,
graphqlUrl: process.env.EXTERNAL_GRAPHQL_URL,
```
1. Add these to any page:
```
import getConfig from "next/config";
const { publicRuntimeConfig } = getConfig();
console.log(publicRuntimeConfig)` 
```
> fix(config): add canonicalUrl to publicRuntimeConfig

- package.json
- src/components/CheckoutActions/CheckoutActions.js
- src/components/OrderFulfillmentGroup/OrderFulfillmentGroup.js
- src/lib/theme/components.js
- src/lib/utils/cartUtils.js
- yarn.lock
Resolves #414 
- Shipping address form is not saving `fullName`
- Shipping address form is not displaying `fullName`
- Submit `fullName` instead of `firstName` and `lastName`
- Display `fullName`
- Upgrades `@reactioncommerce/components`
- Remove `adaptAddressToFormFields` function - No longer needed
1. Fill out the form
2. Look for the name to be displayed in both the form and the completed CheckoutAction
> fix(414): Fullname is not saved or displayed

- package.json
- src/containers/catalog/withCatalogItemProduct.js
- src/lib/apollo/initApollo.js
- src/lib/apollo/withApolloClient.js
- src/server.js
- yarn.lock
Resolves #350
Type: feature
Renew access tokens on 401 errors by redirecting to re-auth
- On 401 errors, redirect to signin endpoint to perform auth and get new access token. Done on both the SSR and browser.
None
If going from product grid to a product's detail page and you have an expired token, the app first shows the Not Found component based on this line of code:
https://github.com/reactioncommerce/reaction-next-starterkit/blob/558d94be01491c26c708d8dea98d6e7528a29bdb/src/pages/product.js#L93
The Not Found page is shown while the redirect is happening. Once redirect flow completes, the product component is then displayed properly. I haven't found a way to fix this. 
1. Start Starterkit on this branch
2. Run Hydra on master. Set this ENV in the docker-compose yaml before starting the …
> feat Renew access tokens on 401 errors using redirects to auth endpoint

- src/components/CheckoutSummary/CheckoutSummary.js
- src/components/OrderSummary/OrderSummary.js
- src/pages/cart.js
Only 1 of the 4 places where `CartSummary` is used was showing the `taxTotal` amount. The others always showed `-`.
Now all summaries show the tax amount
n/a
Must be tested against `refactor-aldeed-split-tax-rates-plugin` branch of Reaction API until it is merged.
1. Configure and enable a tax service in Reaction operator UI.
2. Configure a product variant to be taxable and have a taxable tax code.
3. Add that product variant to your cart in starter kit storefront.
4. Go to checkout and enter a shipping address.
5. Verify that a tax amount shows in the summary on the right
6. Go to `/cart` and verify that a tax amount shows there.
7. Go back to checkout and finish checking out. Verify that a tax amount shows on the order summary after the order is …
> fix: show tax total in all summaries

- src/lib/apollo/withApolloClient.js
- src/server.js
Resolves: NA
When loading the app after a previous authenticated session and the auth token is expired, the app shows a blank screen. The starterkit server logs shows an error about other failures but not explicit about the 401. 
Looking in the browser network tab can help, as the 401 can be seen there.
The Reaction API service logs shows the `Bearer token is not active` error; but it helps to have it logged here too.
Add proper logs that reflect the actual problem (pending when automatic refresh is resolved #350)
@Akarshit adding you as reviewer because you ran into this recently. There's really nothing to test other than confirming that the logged message helps to know the actual issue (and prevents getting stuck).
> chore: Add logger messages for 401 error

- package.json
- src/components/CheckoutActions/CheckoutActions.js
- src/containers/address/query.gql
- src/containers/address/withAddressValidation.js
- src/containers/catalog/withCatalogItems.js
- src/lib/theme/components.js
- yarn.lock
Resolves #366 
#366 
Created a `withAddressValidation` Query container that provides Checkout with the `addressValidation` GQL query method as well as any validation results returned from the validation service.
N/A
*This PR requires Reaction 2.0.0-rc.7*
**Valid addresses**
1. As an Admin within Reaction, open the  "Shop" panel and enable the "Test Validation".
2. As a customer within the Starterkit add an item to the cart and start to check out as a guest.
3. Enter a shipping address that has a `postal` code that starts with "9" (i.e., `90210`).
4. The address should return as valid and checkout should move to the next step.
5. Complete checkout.
**Invalid addresses**
1. As a customer within the Starterkit add an item to the cart and start to check out …
> feat: 366 nnnnat address validation

- src/lib/apollo/withApolloClient.js
Resolves: NA
`const logger = require("lib/logger");`
`logger.debug("")` ==> debug is not a function
In the express app, the exported [Logger](https://github.com/reactioncommerce/reaction-next-starterkit/blob/develop/src/lib/logger/index.js) is custom and only has `error` and `appStarted` methods. It is different from https://github.com/reactioncommerce/logger.
Solution: Switch to plain console.log instead.
1. On token expiration (which is when the incorrect logger was being called), you should see the message printed and not see an error similar to:
```
[Network error]: SyntaxError: Unexpected token U in JSON at position 0
TypeError: _logger__WEBPACK_IMPORTED_MODULE_8___default.a.debug is not a function
at Function._callee$ …
```
> Fix incorrect logger.debug

- src/components/CheckoutActions/CheckoutActions.js
- src/containers/cart/withCart.js
- src/containers/order/fragments.gql
- src/containers/order/queries.gql
- src/containers/order/withOrder.js
- src/lib/tracking/trackOrder.js
- src/pages/checkout.js
- src/pages/checkoutComplete.js
There was no order ID that was provided by GraphQL that could be displayed to the customer and then also seen as a reference ID by the operator. There was a workaround for this in place, decoding the `Order._id` and showing that.
https://github.com/reactioncommerce/reaction/pull/4827 introduces `order.referenceId`. This PR updates the storefront to display that ID on the order completion page.
Tied to a change in Reaction API. Will not work with earlier versions of the API anymore.
See https://github.com/reactioncommerce/reaction/pull/4827 testing instructions
> Use new `order.referenceId` as displayed order ID

- package.json
- src/components/CheckoutSummary/__snapshots__/CheckoutSummary.test.js.snap
- src/components/OrderFulfillmentGroup/__snapshots__/OrderFulfillmentGroup.test.js.snap
- src/components/OrderFulfillmentGroups/__snapshots__/OrderFulfillmentGroups.test.js.snap
- src/containers/cart/fragments.gql
- yarn.lock
Resolves #240 
- When the quantity of a product in a cart is more than 1, the price does not reflect the total price.
- Update to latest Components version
- Add `subtotal` to Carts query
1. Test in MiniCart
2. Test in Cart
3. Test in Checkout
4. Test on Thank you page
5. Test on mobile
> #240:  Add subtotal to CartItems

- src/routes.js
Resolves #441
Some links do not work when `ENABLE_SPA_LINKS=false`
Set a default value for `options`.
None.
1. Set `ENABLE_SPA_LINKS=false` in `.env`
1. Start the app
1. Click on a tag
1. you should be navigated to that tag
> fix: Fix error when clicking links when ENABLE_SPA_LINKS=false

- src/components/CheckoutActions/CheckoutActions.js
- src/containers/address/withAddressValidation.js
Resolves #451 
Type: **fix|enhancement**
Trying to set state asynchronously, sometimes you may run into a warning stating that you can't call `setState`, or `forceUpdate` on a non-mounted component.
1. Search for `this.setState` and `this.forceUpdate`.
2. For any that are in a callback/then, or after an await, add isMounted check as described [here](https://docs.reactioncommerce.com/docs/react-best-practices#setting-state-asynchronously)
N/A
- This is more of a code review and test to confirm that no regression is created for the components touched
> fix: Add proper isMounted checking

- .snyk
- src/components/Profile/ProfileContainer.js
- src/components/VariantItem/VariantItem.js
- src/containers/account/withViewer.js
- src/containers/cart/withCart.js
- src/containers/catalog/withCatalogItemProduct.js
- src/containers/catalog/withCatalogItems.js
- src/containers/order/withOrder.js
- src/containers/shop/withShop.js
- src/containers/tags/withTag.js
- src/lib/apollo/initApollo.js
- src/lib/apollo/withApolloClient.js
Resolves #470 
Due to GraphQL server update to Apollo Server 2.0 as well as subsequent changes in starterkit, the earlier work to silently re-authenticate when a 401 error is detected stopped working.
Revamped how we're doing it to be more foolproof.
None
I recommend testing against https://github.com/reactioncommerce/reaction/pull/4894 or the re-auth from browser will not work.
There are two ways this token refreshing is supposed to work, both of which need to be tested. The setup is the same for both:
- Add `- ACCESS_TOKEN_LIFESPAN=1m` in the `environment` section of reaction-hydra project's `docker-compose.yml` file.
- `dc down` and `dc up -d` reaction-hydra
- Log out of starterkit, and then log back in.
This will force auth tokens to expire after …
> fix: fix logic for retrying 401s with silent re-auth

- .circleci/config.yml
- tests/integration/ssr.test.js
Resolves #456 
Type: **test**
- SSR integration test was failing via CI, not locally.
- Broken link checker was turned off due to flaky environments
Due to SSR need to be rendered on a browser, it needed a way to test it out.
A solution was to add the SSR / integration step as a dependency on the `ecs-deploy` job in CI with an accompanying staging url environment call. Similar to how future e2e tests will run.
To make sure it can be tested for local development, add a ternary conditional operation that defaults to `localhost:4000` if no env variable is set.
Due to the stability of the staging environment, re-activate the broken link checker. 
Runs as a dependency for the `ecs-deploy` job in CI.
1. After successful merge to deploy, validate if tests run in CI
2. Validate …
> chore : integrate ssr test + broken link checker to CI

- src/pages/cart.js
Resolves #465
#465
Update check for empty cart used to show <PageLoading />.
When a user has no item in cart in a new session, this.props.cart is null
When the app is still loading, this.props.cart is undefined
The previous check `if (!this.props.cart)` needs to be a bit specific.
N/A
1. Confirm that cart page now shows properly when there's no item in cart
> fix: Fix infinite loader when cart empty

- src/server.js
- src/sitemapRoutesHandler.js
Part of: reactioncommerce/reaction#4927
Get Sitemap  data from GQL API and make it available on sitemap*.xml routes
Same as reactioncommerce/reaction#4927, pasted below:
- Start reaction on this branch
- Generate Sitemaps by going to the "Shop" admin panel. Under "Options" tab, click "Refresh Sitemap"
- Start the starterkit app with this branch ([feat-4796-impactmass-sitemap-endpoint](https://github.com/reactioncommerce/reaction-next-starterkit/tree/feat-4796-impactmass-sitemap-endpoint)).
- Visit `{starterkitdomain}/sitemap.xml` e.g http://localhost:4000/sitemap.xml 
- You should see the sitemap xml on the page
> feat: Setup sitemap routes to get data from GQL server

- package.json
- src/lib/apollo/initApollo.js
- yarn.lock
Resolves https://github.com/reactioncommerce/reaction/pull/4938
Add support for graphql subscriptions
Update packages and split the `httpLink` to accept subscriptions.
none
Follow testing instructions here: https://github.com/reactioncommerce/reaction/pull/4938
> feat: add graphql subscription support

- src/config.js
- src/server.js
- src/sitemapRoutesHandler.js
Resolves NA
Type: **feature+refactor**
During an internal PR review, some refactor + updates were suggested that I'm adding here:
- Switch `fetch().then.catch()` to async/await
- Bubble up 404 and 500 errors to the error middleware and let them be handled there
- Add Cache-Control header to cache the sitemap. With max-age default of 12 hours. 
- Use express route pattern matching
Testing should be same as the original PR found here https://github.com/reactioncommerce/reaction-next-starterkit/pull/488. You can use reaction's develop branch.
> Add enhancements to sitemap route handling 

- Dockerfile
Our docker image was pretty slim. It was hard to debug and troubleshoot issues in there with docker networking, connected services, config files, etc.
I've added some packages
- essential development/debugging/troubleshooting tools
-  `vim` text editor
-  `curl`  http client
- developer convenience packages 
- `less` non-medieval pager 
- `bash` shell with baseline features like tab completion, history
I've also set the shell for the `Dockerfile` itself to "bash strict mode". It will exit if any command fails, which is usually the correct behavior, and avoids needing to specify `set -e` in every `RUN` line and also eliminates the need to use `&&` as a command separator (`;` is fine with this `SHELL` setting).
I don't believe any of these changes are …
> feat: Add dev utilities to the docker image

- .circleci/bin/calibre-deploy.sh
- .circleci/config.yml
Type: **test**
No standard way of measuring performance metrics on stock Starter Kit. 
Integrate Calibre metric measurement as a step after successful deployment to ECS.
None
1. Verify Calibre snapshots reach to Calibre's Dashboard
2. Verify Calibre runs on CI
Example Output (https://circleci.com/gh/reactioncommerce/reaction-next-starterkit/8269)
```
🇺🇸  Northern California, USA
9:17pm 27-Feb-2019
Performance Grade: 94
Progressive Web App Grade: 32
Best Practices Grade: 100
Accessibility Grade: 79
SEO Grade: 100
Timing
Time to First Byte
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 595 ms
Response time
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 807 ms
First Meaningful Paint …
```
> feat : performance metrics integration with calibre

- Dockerfile
Resolves #513 
Impact: **breaking**
Starterkit docker container was throwing errors, and not being created:
```
ERROR: unsatisfiable constraints:
curl-7.61.1-r2:
breaks: world[curl=7.61.1-r1]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk --no-cache add bash=4.4.19-r1 curl=7.61.1-r1 less=530-r0 vim=8.1.0115-r0' returned a non-zero code: 1
```
Remove two lines of code contributing to this error. It seems like this code might have been transferred over from https://github.com/reactioncommerce/reaction-cli, and isn't working in its current form.
1. Clone `reaction-platform`
1. run `make`
1. See that `starterkit` starts with no errors
> remove blocking code to allow starterkit to start

- src/custom/componentTheme.js
Resolves #510 
Type: **docs**
The theming example at `src/custom/componentTheme.js` is outdated and doesn't work anymore.
Update the component theming example.
None.
1. Open `src/custom/componentTheme.js`.
2. Uncomment line 13 to 17.
3. Browse localhost:4000/cart with an empty cart.
4. See that the background color of the "Continue shopping" button has changed.
> fix: Update component theming example

- .snyk
Type: **chore|security**
We have a snyk vuln deep in our dep tree that is non-trivial to avoid with npm dependency updates at this time.
Delay 30 days and hope some new deps show up that don't break when we update.
N/A
N/A
> chore: ignore snyk js-yaml vuln for 30 days

- .circleci/config.yml
- package.json
- src/serverAuth.js
Resolves #519 
Type: **bugfix|style|chore**
See #519 
Make sure each code branch performs some type of express response.
N/A
See #519 
If you log out while reaction core is down, you'll see a plain text response with this error in your browser, but at least it's an intelligible error message not just a loading spinner
```
Error while logging out: request to http://reaction.api.reaction.localhost:3000/logout?userId=uG4sZqiJuZPY8LFJ3 failed, reason: connect ECONNREFUSED 127.0.0.1:3000
```
> Always send a response to logout requests

- src/containers/catalog/catalogItemProduct.gql
Removes some fields from the GraphQL query because they aren't used and https://github.com/reactioncommerce/reaction/pull/5164 will remove these fields from being available once it is merged.
Verify that the pages related to catalog items work as expected. This can be tested and merged before the linked API PR.
> feat: remove unused fields from GQL query

- package.json
Fixes this warning: 
```
● Validation Warning:
Unknown option "prettier" with value {"arrowParens": "always"} was found.
This is probably a typing mistake. Fixing it will remove this message.
Configuration Documentation:
https://jestjs.io/docs/configuration.html
```
> fix: prettier config was in the wrong place

- .circleci/bin/calibre-deploy.sh
- .circleci/config.yml
Type: **performance|chore**
It is recommended to avoid using `sudo` as much as possible which was being used to install `calibre` globally as part of the CI step. Due to not specifying the version of `calibre` there was a failure in the CI steps.
Change from `sudo npm install calibre` to `npx calibre@x.y.z`
> fix: change calibre ci step to use npx

- package.json
Resolves #509 
Type: **docs|chore**
The license in the `package.json` does not match the LICENSE.md and README.md licenses. The `package.json` uses GPL, but this repo is Apache.
Add `"license": "Apache-2.0"` to package.json
> chore(license): match license from LICENSE.md and README

- README.md
Resolves 501
Type: **docs**
This resolves part of https://github.com/reactioncommerce/reaction-next-starterkit/issues/501 - answers this question: `I would like to run the started kit locally, but sometimes connected to externally hosted staging Reaction GraphQL server on Digital Ocean.`
Add the command: `docker-compose run --rm --service-ports web yarn dev`
It's tricky cos you gotta add `--service-ports`
none
1. Try this command out
> docs(README): add instructions on how to run starterkit w/ prod API

- README.md
Type: **developer happiness**
The command in the README currently doesn't work.
Remove `babel-node` and use `node` instead, like the current `yarn start` script does.
1. Try `docker-compose run --rm --publish 9229:9229 --publish 4000:4000 -e NODE_ENV=development web babel-node --inspect=0.0.0.0:9229 ./src/server.js` and confirm it doesnt work.
1. Try `docker-compose run --rm --publish 9229:9229 --publish 4000:4000 -e NODE_ENV=development web node --inspect=0.0.0.0:9229 ./src/server.js` instead.
> chore(development): fix debugger command in README

- .circleci/bin/should-run-snyk.sh
- .circleci/config.yml
- Dockerfile
Every PR against this repo was running the snyk security CI test. These tests would sometimes fail when our "ignore this vuln for 30 days" period expired. This would cause a roadblock for contributions and other feature work.
**However**, this PR might be wholly unnecessary as there's a snyk setting on the github repo that possibly achieves the same thing.
Only run snyk when package.json changes. This is the same approach we are using in reactioncommerce/reaction.
None
This scripting is not readily able to be locally tested due to circleci limitations, so we can only look at the output of circleci jobs to verify it's passing and doing what's expected.
I extracted the main logic from the `.circleci/config.yaml` we have in rc/reaction. Made it into a …
> chore: only run snyk when package.json changes

- src/next.config.js
Resolves #503 
Impact: minor
Type: bugfix
The `styled-components` package was being loaded twice.
Add a resolve alias to the WebPack config to import only the es modules version of `styled-components`
1. Start storefront
2. Inspect browser console, and verify there is no error regarding duplicate `styled-components`
> fix: de-duplicate styled-components package

- README.md
Resolves #487 
Type: **docs**
This project is our example for how to build a storefront on top of the headless [Reaction Commerce GraphQL API](https://github.com/reactioncommerce/reaction). This PR removes the "Not Ready For Production" warning from the README for this project. This project does not yet provide a feature-complete implementation of the GraphQL API, but it is does provide an example of how to build a storefront that consumes the Reaction Commerce API.
> docs: remove production warning

- .env.example
- .graphqlrc
- Dockerfile
- README.md
- docker-compose.yml
- docs/README.md
- docs/static-assets.md
- docs/theming.md
- docs/tracking-events.md
- docs/utilities.md
- package.json
Resolves #476 
Impact: **breaking|critical|major**
Type: *chore**
This project was long due for a rename as the "starterkit" name caused some confusion. 
This PR get's this project ready for the official 2.0 release by changing the project/repo name to "example-storefront", updating configs to use the `graphql-beta` endpoint and some copy/docs updates.
n/a
> chore: rename project to example-storefront

- CHANGELOG.md
- package.json
The updates to CHANGELOG and version weren't put into develop branch due to the rc candidate being cut develop -> rc -> master before.
- Updated CHANGELOG to include RC10, RC11, and RC12
- Bump Version for RC 12 from RC 9 on Develop
> chore: update CHANGELOG, bump version to rc 12

- src/server.js
Signed-off-by: Christopher Shepherd <christopher@reactioncommerce.com>
Resolves #549 
Adds 302 redirects for a few paths via express.js
Added redirects at the express.js level rather than the next.js router because I don't see a downside to it, and it's easy to express in just a few lines of code.
none
1. curl -i http://localhost:4000/graphiql (or /graphql, or /graphql-alpha or /graphql-beta)
2. Observe HTTP 302 redirect to EXTERNAL_GRAPHQL_URL
> Add 302 redirects to env.EXTERNAL_GRAPHQL_URL

- README.md
Impact: **|minor**
Type: **docs**
I think the `/graphiql` path doesn't work in reaction core anymore so I removed it and we can just have 1 place to go for graphql: `/graphql-beta` on core.
Added notes about the storefront->core redirects we added yesterday.
> docs: Adjust graphiql URLs links and docs

- src/components/VariantList/VariantList.js
Resolves #5263
Prevent crash on PDP page caused by not checking for variant existence before passing to inventory status component.
1. Start reaction
2. Go to homepage
3. Go to product
4. Go back to home page
5. Go to other product
6. Verify PDP does not crash
> hotfix: prevent app crash on PDP page.

- README.md
Signed-off-by: Machiko Yasuda <machiko@reactioncommerce.com>
Type: **docs|core**
- Don't call it the Reaction Component Library anymore
- Call it the Example Storefront Component Library (or Storefront Component Library for short)
- Rename the names
- Update 2018 to 2019
No
1. Read the docs
> docs(readme): component library naming

- .circleci/config.yml
- .reaction/entrypoint.sh
- .reaction/fix-volumes.sh
- Dockerfile
- Dockerfile.dev
- bin/fix-volumes
- docker-compose.yml
- package.json
- yarn.lock
Type: **feature|bugfix**
On linux, the docker container runs as user `node` (uid 1000), which in many cases is not the same as the developer's host OS uid. This can cause mismatches in ownership of files that are shared between the host and the container via docker volume mounts. Ultimately this surfaces as filesystem errors (`EACCESS`, `permission denied`, etc) at various times including when trying to run `yarn`, do builds, etc.
**Why doesn't bug  affect all linux users?**
On many linux distributions, the first non-system user is assigned uid 1000. That's why in our docker container the `node` user has uid 1000, it's just a default. That's also why many developer's have uid 1000 as well: it's the default for the first non-system user on their distribution and their …
> feat: get host uid:gid and use in docker

- .circleci/config.yml
Fix broken e2e tests by adding a checkout step in circleci.
> fix: e2e tests need a checkout step now

- package.json
Example Storefront v2.4.0 is a minor update to keep this project in sync with [Reaction v2.4.0](https://github.com/reactioncommerce/reaction) and [reaction-hydra v2.4.0](https://github.com/reactioncommerce/reaction-hydra)
feat: Use host uid:gid and use in docker to avoid file permissions problems [#576](https://github.com/reactioncommerce/example-storefront/pull/576)
fix: Resolve broken e2e tests by adding a checkout step in CircleCI [#580](https://github.com/reactioncommerce/example-storefront/pull/580)
None
> chore: bump version to 2.4.0 in package.json

- docker-compose.yml
I removed this volume mount in some prior work not understanding it's necessity.
Add it back with a comment justifying its existence.
N/A
1. Bring up storefront (especially on mac)
1. Locally run `yarn` on your host
1. Configure your editor to use the project-specific eslint
1. Confirm IDE/editor based linting works OK from host OS
1. Confirm app runs fine in docker at same time
> fix: restore empty_node_modules volume

- CHANGELOG.md
- docker-compose.yml
- package.json
Example Storefront v2.6.0 is a minor update to keep this project in sync with [Reaction v2.6.0](https://github.com/reactioncommerce/reaction) and [reaction-hydra v2.6.0](https://github.com/reactioncommerce/reaction-hydra
> Release v2.6.0

- .circleci/config.yml
After we push the newly built Docker image for this service to DockerHub, we want to deploy it to an internal Kubernetes cluster.
We create a pull request against the reactioncommerce/reaction-gitops repository. The only modified file in this pull request is a special kustomization.yaml file which will contain the proper Docker image tag for the newly built Docker image. Once that PR is merged, the deploy will happen via a Gitops workflow.
Make sure a PR is created against reaction-gitops.
> add step for PR creation against the reaction-gitops repo

- CHANGELOG.md
- package.json
Example Storefront v2.9.0 is a minor update to keep this project in sync with [Reaction v2.9.0](https://github.com/reactioncommerce/reaction) and [reaction-hydra v2.9.0](https://github.com/reactioncommerce/reaction-hydra)
> release v2.9.0

- CHANGELOG.md
- package.json
Example Storefront v2.8.1 is a patch update to keep this project in sync with [Reaction v2.8.1](https://github.com/reactioncommerce/reaction) and [reaction-hydra v2.8.1](https://github.com/reactioncommerce/reaction-hydra)
> release v2.8.1

- src/components/CheckoutActions/CheckoutActions.js
- src/containers/tags/tag.gql
- src/containers/tags/withTag.js
Resolves #620 
Due to breaking changes in the 3.0 `tag` GraphQL query, the example storefront does not load.
Update client query to match API.
Yes, this won't work with 2.x API, but this is the 3.0 branch.
Verify storefront loads in browser when connected with `release-3.0.0` branch of API, and you don't see any errors in the API or storefront server logs.
> [3.0.0] Fix params for withTag API query

- bin/setup
Impact: **major**  
The general problem is that the `find` used in `bin/setup` is run from the PWD the script is run from.
The expected outcome is that `bin/setup` should only copy environment variables found within this project.
Right now running `make init` in reaction-platform copies the environment variables from _every_ project's `.env.example` files into almost every `.env` file of every other project.
This is because in this case the `find` command used to find all `.env.example` files is being run from the platform directory, and thus all cloned projects within it are found by the `find`.
I made `bin/setup` `cd` to the root of the project before running the `find`.
This also prevents us from needing the `$__dir` variable we were using when referring to files …
> fix: made bin/setup always run from the desired path

- .gitignore
- bin/start-prod.sh
- docker-compose.dev.yml
- docker-compose.yml
When you clone this branch and run `docker-compose up`, it will now pull and use the latest published `reactioncommerce/example-storefront:release-v3.0.0` image from DockerHub instead of `node-dev`. Host files are not linked in, NPM deps are not reinstalled, and NextJS will run in the faster production mode unless you set `NODE_ENV=development` in your `.env` file.
Breaking only for devs who will now need to run `ln -s docker-compose.dev.yml docker-compose.override.yml` to get the previous behavior.
- Verify `dc up` starts quickly and in prod mode. (You should not see anything about compiling pages in the logs.)
- After `dc down`, run `ln -s docker-compose.dev.yml docker-compose.override.yml` and then `dc up` again. Verify it now starts in dev mode and …
> chore: use published image for docker-compose

- src/containers/cart/queries.gql
- src/containers/cart/withCart.js
Storefront was unusable because carts weren't being create / read due to missing one instance when renaming a param.
Update the param name.
None
1. See that you can add items to cart on storefront
> fix: update param name which was missed

- .env.example
- src/config.js
- src/serverAuth.js
See https://github.com/reactioncommerce/reaction/pull/5951
Impact: **critical**  
You need to be [this branch of Reaction](https://github.com/reactioncommerce/reaction/pull/5951) when testing. That PR and this one should be merged at the same time.
Account login was not working when trying to login via example storefront.
Add `oauth` login method to new `AuthContainer`. This is how we used to do oauth login in the past, when we used `OauthContainer`, but this was removed / with the new `AuthContainer`.
None
1. Start the full app (reaction (https://github.com/reactioncommerce/reaction/pull/5951) / storefront)
1. Navigate to storefront
1. Login
1. See you are redirected back to storefront, and you are logged in
1. Logout
1. See you are redirected back to storefront, and are …
> fix: login from storefront

- CHANGELOG.md
- package.json
All changes are already in the `release-3.0.0` branch. This simply adds the info into the CHANGELOG, and changes the version number in the `package.json`.
Once this is merged, we will create a release from the `release-3.0.0` branch.
_____
Example Storefront v3.0.0-alpha.2 is the second alpha release of the Example Storefront that is designed to work with our new Reaction API.
*Reaction releases will no longer be coordinated across all projects - we'll release each project, independently, as needed. This means version numbers will no longer be in sync. The newest versions of each project will work together.*
- feat: auto-create Hydra client on startup [#628](https://github.com/reactioncommerce/example-storefront/pull/628)
- chore: use published image for docker-compose …
> release v3.0.0-alpha.2
